update t_quest set tag = '燕雀石' where id = 319;#清晨大骚动
update t_quest set tag = '铠玉' where id = 320;#大胃王们来了！
update t_quest set tag = '松软票(双刀外观)' where id = 321;#天黑前的片刻
update t_quest set tag = '苍星碎片(太刀外观)' where id = 322;#日本环球影城·跃动吧，金星们！
update t_quest set tag = '钢针票(大锤外观)' where id = 323;#暴徒早起散步
update t_quest set tag = '上铠玉' where id = 324;#共斗鸟×鸟
update t_quest set tag = '餐券' where id = 325;#打开食欲之门!
update t_quest set tag = '名匠的设计图(大剑外观)' where id = 326;#猎人们永远的梦想
update t_quest set tag = '上铠玉' where id = 327;#地盘争夺决定战
update t_quest set tag = '上铠玉' where id = 328;#狩猎骨肉
update t_quest set tag = '勇气之证' where id = 329;#双幻影
update t_quest set tag = '勇气之证' where id = 330;#长有翅膀者有毒
update t_quest set tag = '第一期团票(长枪|旗子外观)' where id = 331;#深夜大骚动
update t_quest set tag = '伪装票' where id = 332;#猪菌是菌但也是香菇的菌
update t_quest set tag = '熔山龙的热鳞' where id = 333;#看见曙光
update t_quest set tag = '黑色绷带(眼罩外观)' where id = 334;#我们是不良
update t_quest set tag = '黑水晶票(墨镜外观)' where id = 335;#抵抗强光的人们
update t_quest set tag = '搔鸟票(搔鸟头套)' where id = 336;#爱上蛋吧！
update t_quest set tag = '摇曳鳗票(摇曳鳗头套)' where id = 337;#身心都是摇曳鳗
update t_quest set tag = '发光宝珠' where id = 338;#咚咚咚三兄弟
update t_quest set tag = '伪装票' where id = 339;#两位女王
update t_quest set tag = '伪装票2' where id = 340;#无惧于空中飞人
update t_quest set tag = '尖铠玉' where id = 341;#爆锤龙们翻倒了！
update t_quest set tag = '尖铠玉' where id = 342;#深绿的蓝调
update t_quest set tag = '尖铠玉' where id = 343;#荒野的波丽露
update t_quest set tag = '尖铠玉' where id = 344;#海台的华尔兹
update t_quest set tag = '尖铠玉' where id = 345;#荒废之谷的歌剧
update t_quest set tag = '尖铠玉' where id = 346;#结晶体的摇滚乐
update t_quest set tag = '尖铠玉' where id = 347;#暴动亦如是
update t_quest set tag = '洛克人票(艾露猫防具)' where id = 348;#斩击大骚动！！？
update t_quest set tag = '苍星宝玉(苍星太刀|防具)' where id = 349;#日本环球影城·燃燒喲，蒼星們！
update t_quest set tag = '红魔魂石(盾斧外观|但丁防具)' where id = 350;#代码:红
update t_quest set tag = '塞努的发翔羽(刺客衣装|巴耶克外观)' where id = 351;#惨静，恐暴，艳热
update t_quest set tag = '老旧宝珠' where id = 352;#穷贼啮猎人！
update t_quest set tag = '风化的宝珠' where id = 353;#本尊的名字是熔岩龙
update t_quest set tag = '尸套龙票(乌尔德外观)' where id = 354;#寂静之幕
update t_quest set tag = '幻兽票(麒麟外观)' where id = 355;#隐藏的白色鬃毛也
update t_quest set tag = '炎王龙票(帝王外观)' where id = 356;#太阳熊熊燃烧之时
update t_quest set tag = '钢龙票(钢龙外观)' where id = 357;#在暴风雨中
update t_quest set tag = '灭尽龙票(战纹外观)' where id = 358;#毁灭来临，喇叭作响
update t_quest set tag = '炎妃龙票(皇后外观)' where id = 359;#青出于爱而更胜其爱
update t_quest set tag = '龙脉石' where id = 360;#脉动，本能
update t_quest set tag = '熔山龙的热鳞' where id = 361;#不灭之黎明破晓
update t_quest set tag = '冥灯龙票(冥灯龙外观)' where id = 362;#此乃古龙之王
update t_quest set tag = '勇气之证·大' where id = 363;#冥河的卡戎
update t_quest set tag = '良质硬骨' where id = 364;#交货顺便调查痕迹
update t_quest set tag = '白鸠石' where id = 365;#交货，不管怎样就是要痕迹
update t_quest set tag = '尖铠玉' where id = 366;#山丘上的雪见樱
update t_quest set tag = '发光宝珠' where id = 367;#调查(蛮颚龙，苍火龙)
update t_quest set tag = '发光宝珠' where id = 368;#不守秩序者，前途黯淡
update t_quest set tag = '大龙脉石' where id = 369;#谁对王座露出獠牙？
update t_quest set tag = '幻象棱晶' where id = 370;#贝希摩斯歼灭战
update t_quest set tag = '古代鹿首精的讨伐之证' where id = 371;#委托：林妖
update t_quest set tag = '银猴票券(温泉银猴头套)' where id = 372;#抓住银猴！
update t_quest set tag = '企鹅票(企鹅头套)' where id = 373;#捉到胖衣企鹅！
update t_quest set tag = '龙人族票|太古的宝珠(龙人耳外观)' where id = 374;#美丽的东西会冻伤
update t_quest set tag = '松软票2(柔毛秧鸡头套|稀有生物)' where id = 375;#朝天空狙击！
update t_quest set tag = '磨刀鲹鱼票(双刀外观|刷点磨刀鳞片!!!)' where id = 376;#那条鱼锋利的吗？
update t_quest set tag = '草食票1(精灵鹿头套)' where id = 377;#光明珍珠是圆圆的眼神
update t_quest set tag = '冷冻票券(大剑外观-咸鱼)' where id = 378;#这条鱼不适合进食
update t_quest set tag = '顽强重骨' where id = 379;#地底之主正在呼唤...
update t_quest set tag = '绯鸢石' where id = 380;#干地的宝石果实
update t_quest set tag = '猛牛龙的重壳' where id = 381;#拘泥于沼泥的猛牛们
update t_quest set tag = '巧克力' where id = 382;#新世界
update t_quest set tag = '阿尔忒弥斯的笔记本' where id = 383;#我们的世界
update t_quest set tag = '草食票2(草食龙头套)' where id = 384;#女王的食桌
update t_quest set tag = '金蛋' where id = 385;#好坏孩子统统入睡
update t_quest set tag = '摇曳鳗壶(艾露猫防具-摇曳鳗|稀有生物)' where id = 386;#猎人们永远的梦想2
update t_quest set tag = '飞雷票(围巾外观|小金飞雷龙|大金麻痹龙)' where id = 387;#雷龙小雷龙大雷龙
update t_quest set tag = '太古的宝珠' where id = 388;#真正的暴徒是哪个？！
update t_quest set tag = '强龙骨' where id = 389;#睡眠与麻痹的组合
update t_quest set tag = '幻鸟龙玉' where id = 390;#缤·纷·色·彩
update t_quest set tag = '祭典票(宫廷系列武器外观)' where id = 391;#斗技场的白色情书
update t_quest set tag = '黑鹰的设计图(大剑喷气外观|盾斧黑鹰外观)' where id = 392;#猎人们永远的梦想3
update t_quest set tag = '太古的宝珠' where id = 393;#焚天之王，游火之哲
update t_quest set tag = '太古的宝珠' where id = 394;#在乎荒地发生的事
update t_quest set tag = '太古的宝珠' where id = 395;#水与冰气正在等候
update t_quest set tag = '重龙骨' where id = 396;#燃烧吧，兽龙种！！！！
update t_quest set tag = '用餐地区票【酒】(双刀外观)' where id = 397;#稀幻的轰龙？？？
update t_quest set tag = '刻印的宝珠' where id = 398;#轰与迅的热切邂逅
update t_quest set tag = '用餐地区票【肉】(双刀外观)' where id = 399;#饥饿不等人
update t_quest set tag = '太古的宝珠' where id = 400;#不候人的全力疾走
update t_quest set tag = '太古的宝珠' where id = 401;#适合地底
update t_quest set tag = '刚龙骨' where id = 402;#森林深处
update t_quest set tag = '十字鎬票(太刀外观)' where id = 403;#粉碎矿山
update t_quest set tag = '封印的龙骸布(头部外观)' where id = 404;#古龙来临，冰冻三尺
update t_quest set tag = '太古的宝珠(刷MR等级)' where id = 405;#三界主
update t_quest set tag = '古龙的净血' where id = 406;#永冻冬季
update t_quest set tag = '太古的宝珠' where id = 407;#饥渴的理由
update t_quest set tag = '金之炼金票' where id = 408;#老士的脱俗
update t_quest set tag = '重铠玉(刺客衣装·改)' where id = 409;#暗杀者
update t_quest set tag = 'S.T.A.R.S.徽章(里昂|克莱尔防具|武器饰物)' where id = 410;#RE: 生物危害重归大地
update t_quest set tag = '苍世之证(上位苍星防具|苍星弓)' where id = 411;#日本环球影城·无限的闪耀
update t_quest set tag = '苍世的大宝玉(大师苍星防具|苍星太刀)' where id = 412;#日本环球影城·舞动霜刃！
update t_quest set tag = '好友之证' where id = 413;#调查（雷狼龙，溟波龙）
update t_quest set tag = '太古的宝珠' where id = 414;#踢地跨月
update t_quest set tag = '太古的宝珠' where id = 415;#我既优雅又充满良心
update t_quest set tag = '太古的宝珠' where id = 416;#破天大轰
update t_quest set tag = '太古的宝珠' where id = 417;#银色逆光
update t_quest set tag = '太古的宝珠' where id = 418;#月亮是无慈悲的金女王
update t_quest set tag = '健美票(健美阿尔法防具)' where id = 419;#噢，健美身体
update t_quest set tag = '健美票Ｇ(健美伽马防具)' where id = 420;#噢噢，健美身体
update t_quest set tag = '太古的宝珠' where id = 421;#力量是金
update t_quest set tag = '太古的宝珠' where id = 422;#暴虐与不合理乃伤痕之母
update t_quest set tag = '太古的宝珠' where id = 423;#八万地狱之狼
update t_quest set tag = '重铠玉' where id = 424;#大树的约德尔
update t_quest set tag = '重铠玉' where id = 425;#温泥的重金属
update t_quest set tag = '重铠玉' where id = 426;#海底的古典乐
update t_quest set tag = '重铠玉' where id = 427;#生命的颂歌
update t_quest set tag = '重铠玉' where id = 428;#粗暴的另类摇滚
update t_quest set tag = '重铠玉' where id = 429;#冰封的谣曲
update t_quest set tag = '封印的宝珠' where id = 430;#雷霆鸣神，降临
update t_quest set tag = '大灵脉玉(你需要很多!!!)' where id = 431;#歼灭之钟，再次作响
update t_quest set tag = '绕行兔票(兔耳朵|小金黑狼鸟)' where id = 432;#塞耳露耳
update t_quest set tag = '温泉金票(温泉候头套|小金激昂金狮子)' where id = 433;#金狮金猴
update t_quest set tag = '三眼票(内衣外观-阿尔法/贝塔)' where id = 434;#身裸万象
update t_quest set tag = '黑色的头巾(头部外观)' where id = 435;#彼岸泪
update t_quest set tag = '特大龙脉炭(大小金雷狼龙)' where id = 436;#再会了，雷狼龙
update t_quest set tag = '黑轰龙票(健美外观|涩的)' where id = 437;#黑轰龙不会受伤
update t_quest set tag = '大灵脉玉(金色大粪-两坨!!!)' where id = 438;#你是黄金奖杯
update t_quest set tag = '封印的宝珠(开局火)' where id = 439;#暗夜恒星
update t_quest set tag = '封印的宝珠(开局冰)' where id = 440;#黎明死星
update t_quest set tag = '封印的宝珠' where id = 441;#风暴的棺材
update t_quest set tag = '封印的宝珠(R12饰品珠!!!达人2!攻击2!放音2!出货啊啊啊!!!)' where id = 442;#灭日
update t_quest set tag = '封印的宝珠' where id = 443;#我的高贵灵魂
update t_quest set tag = '溟波龙票(触角伽马套)' where id = 444;#溟呼远响
update t_quest set tag = '冰牙龙票(各种武器|两套有点帅的防具|艾露猫防具|但是白色大粪!)' where id = 445;#最后的白骑士
update t_quest set tag = '冰呪龙票(雪崩伽马|是你的王冰老师!)' where id = 446;#雪花沉睡
update t_quest set tag = '封印的宝珠' where id = 447;#传说中的黑龙
update t_quest set tag = '坚铠玉' where id = 448;#巨大气球x巨大气球
update t_quest set tag = '重铠玉' where id = 449;#熏火山堆
update t_quest set tag = '刻印的宝珠(绚辉龙武器|领取前换上想刷的武器-后三个奖励|务必破头!)' where id = 450;#无终止的淘金记
