insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','大痹贼龙的牙','45_10.png','大痹贼龙的素材。容易通过破坏头部部位获得。拥有赋予麻痹属性的性质。',4,99,750,750);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','火龙的翼爪','45_1.png','从雌火龙或火龙身上取得的素材。容易通过破坏两翼部位获得。',4,99,1090,1090);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','幻兽的雷尾','41_0.png','麒麟的上位素材。主要通过报酬获得。与雷属性的兼容性佳。',7,99,2430,2430);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','爆锤龙的颚','60_4.png','爆锤龙的上位素材。容易通过破坏颚获得。材质特殊，只能用于限定的装备。',6,99,2980,2980);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','爆鳞龙的爆腺','41_1.png','爆鳞龙的上位素材。容易通过破坏头部部位获得。拥有赋予爆破属性的性质。',6,99,4000,4000);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','猛者龙脉石·刃','65_0.png','历战的猛者所拥有的素材。秘藏着可激发出片手剑、双剑超越极限性能的力量。',6,10,100000,10000);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','第五舰队票','26_13.png','A 票 with the 第五舰队 sflag and emblem. Redeem atthe Smithy for something nice!?',4,99,4000,400);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','樱火龙的重壳','46_8.png','樱火龙的大师级素材。主要经由报酬获得。材质坚硬，常用于防具上。',9,99,35300,3530);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','惨爪龙的强硬筋','41_14.png','惨爪龙的大师级素材。主要经由报酬获得。材质坚硬，常用于防具上。',10,99,43500,4350);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','银火龙的重壳','46_10.png','银火龙的大师级素材。主要经由报酬获得。材质坚硬，常用于防具上。',11,99,66700,6670);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','冰牙龙的厚毛皮','44_0.png','冰牙龙的大师级素材。主要经由剥取获得。泛用性高、用途广泛。',10,99,44100,4410);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','迅龙的厚鳞','43_10.png','迅龙的大师级素材。主要经由剥取获得。材质坚硬，常用于防具上。',10,99,29400,2940);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','黑轰龙的重牙','45_10.png','黑轰龙的大师级素材。容易经由破坏头部部位获得。常用于武器上。',10,99,77200,7720);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','雷狼龙的刚爪','45_12.png','雷狼龙的大师级素材。容易经由破坏两边前脚获得。材质尖锐，常用于武器上。',9,99,74600,7460);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','雷狼龙的天玉','47_12.png','雷狼龙的大师级素材。用在装备上的话，据说能制成统御天地的梦幻稀有品。',11,99,180000,18000);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','狱狼龙的重壳','46_10.png','狱狼龙的大师级素材。主要经由报酬获得。材质坚硬，常用于防具上。',9,99,66300,6630);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','炎王龙的刚角','45_1.png','炎王龙的大师级素材。容易经由破坏头部部位获得。常用于武器上。',11,99,92800,9280);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','溟波龙的韧尾','52_5.png','溟波龙的大师级素材。容易经由切断的尾巴获得。材质强韧，常用于防具上。',11,99,92800,9280);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','煌黑龙的凶爪','45_5.png','煌黑龙的大师级素材。散发着阴暗诡魅的气氛，恐怕只能用穷凶恶极来形容。',11,99,80000,8000);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','美好的鳞片','43_14.png','利用盗掠衣装获得的素材。 收藏家垂涎欲滴的顶级品。（换金道具）',10,99,100000,10000);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','瘴气的结晶','22_24.png','可在聚魔之地的瘴气地带采掘的珍贵矿石。受地脉影响越大，结晶的体积也越大。',9,99,12000,1200);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','龙脉的强龙骨','42_14.png','从栖息于聚魔之地的大型怪物身上采集的骨素材。可能是受到地脉影响，具有惊人的威猛气场。',9,99,20000,2000);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','历战的大水喉袋','13_25.png','历战水妖鸟的大师级素材。在聚魔之地争夺霸权的强者所持有的，经过强化的素材。',9,99,45000,4500);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','历战的黑毛皮','44_5.png','历战浮眠龙的大师级素材。在聚魔之地争夺霸权的强者所持有的，经过强化的素材。',9,99,45000,4500);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','破魂凶爪','45_0.png','凶爪龙大师级素材。栖息在聚魔之地的个体，使其特质更加强化的素材。',10,99,35000,3500);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','红莲的爆鳞','43_0.png','红莲爆鳞龙的大师级素材。栖息在聚魔之地的个体，使其特质更加强化的素材。',11,99,40000,4000);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','惊魂夜票','26_16.png','参加星辰祭【惊魂夜】就能获得的票券。可以用来交换特别的装备或烟火。',9,99,4000,400);
insert into t_items (`cate`, `tag`, `name`, icon, `desc`, rarity, carry, buy, sell) values('material','reward','草食票1','26_2.png','细腻描绘了精灵鹿悠游于大自然样貌的票券。交给加工屋就会有好事发生！？',10,99,8000,800);
